import { useEffect, useRef, useState } from 'react'
import type { Settings } from '../types'

export function SettingsPage({ settings, onChange, onExport, onImport, onClear }: { settings: Settings; onChange: (value: Settings) => void; onExport: () => void; onImport: (file: File) => void; onClear: () => void }) {
  const fileRef = useRef<HTMLInputElement>(null)
  const [saved, setSaved] = useState(false)
  const [aiConfigured, setAiConfigured] = useState<boolean | null>(null)
  useEffect(() => { fetch(import.meta.env.VITE_API_URL || '/api/generate-cards').then((response) => response.json()).then((data) => setAiConfigured(Boolean(data.configured))).catch(() => setAiConfigured(false)) }, [])
  const patch = (value: Partial<Settings>) => { onChange({ ...settings, ...value }); setSaved(true); setTimeout(() => setSaved(false), 1200) }
  return <main className="page"><header className="section-header"><div><span className="eyebrow">按你的节奏</span><h1>设置</h1>{saved && <p className="saved">已保存</p>}</div></header><section className="settings-card"><h2>每日学习数量</h2><div className="form-grid"><label className="field"><span>新句</span><input type="number" min="1" max="20" value={settings.newPerDay} onChange={(event) => patch({ newPerDay: Number(event.target.value) })} /></label><label className="field"><span>复习</span><input type="number" min="0" max="20" value={settings.reviewPerDay} onChange={(event) => patch({ reviewPerDay: Number(event.target.value) })} /></label></div></section><section className="settings-card"><h2>英语偏好</h2><label className="field"><span>口音</span><select value={settings.accent} onChange={(event) => patch({ accent: event.target.value as Settings['accent'] })}><option value="en-US">美式英语</option><option value="en-GB">英式英语</option></select></label><label className="field"><span>AI 难度</span><select value={settings.difficulty} onChange={(event) => patch({ difficulty: event.target.value as Settings['difficulty'] })}><option value="easy">简单</option><option value="daily">日常</option><option value="challenging">稍有挑战</option></select></label><label className="switch"><span>自动播放英语</span><input type="checkbox" checked={settings.autoPlay} onChange={(event) => patch({ autoPlay: event.target.checked })} /></label><label className="switch"><span>显示中文</span><input type="checkbox" checked={settings.showChinese} onChange={(event) => patch({ showChinese: event.target.checked })} /></label></section><section className="settings-card"><h2>豆包 API</h2><div className="status"><i className={aiConfigured ? 'online' : ''} />{aiConfigured === null ? '正在检测…' : aiConfigured ? '已配置 · 真实豆包' : '未配置'}</div><p className="muted">只调用服务端豆包接口；未配置时不会返回 Mock。密钥不会进入浏览器。</p></section><section className="settings-card"><h2>学习数据</h2><div className="stack-actions"><button className="secondary" onClick={onExport}>导出学习数据 JSON</button><button className="secondary" onClick={() => fileRef.current?.click()}>导入学习数据 JSON</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={(event) => event.target.files?.[0] && onImport(event.target.files[0])} /><button className="danger-button" onClick={() => confirm('确定清空学习记录？卡片会保留。') && onClear()}>清空学习记录</button></div></section></main>
}
